### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by rtimush** [rallyhealth/sbt-git-versioning#20]
Hi. It seems that this plugin will be affected by the upcoming shutdown of Bintray. Do you have any plans to move to Maven Central or any other alternative public repository?

**Comment by mpociecha** [comment]
E.g. https://scala.jfrog.io/ui/repos/tree/General/sbt-plugin-releases It would be nice to have it migrated. :pray:

**Comment by robertbutacu** [comment]
are there plans to push the project to maven or sonatype? 
We can't seem to be able to retrieve it

**Comment by thiloplanz** [comment]
There is a 1.6.0 on Maven Central that seems to work:
https://repo1.maven.org/maven2/com/rallyhealth/sbt/sbt-git-versioning_2.12_1.0/1.6.0/

**Comment by nafg** [comment]
So should this be closed?
